### ISSUE TITLE
Pylint 2.6.1 causes AttributeError: module 'pylint.checkers.utils' has no attribute 'is_call_of_name'

### ISSUE THREAD

**Issue by sergeyklay** [PyCQA/pylint-plugin-utils#19]
It appears that the recently released Pylint 2.6.1 may have broken compatibility with this package.

```
$ pylint 
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.9.1/x64/lib/python3.9/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/home/runner/work/python-airslate/python-airslate/.venv/lib/python3.9/site-packages/pylint/lint/check_parallel.py", line 69, in _worker_check_single_file
    _worker_linter.check_single_file(name, filepath, modname)
  File "/home/runner/work/python-airslate/python-airslate/.venv/lib/python3.9/site-packages/pylint/lint/pylinter.py", line 881, in check_single_file
    self._check_file(
  File "/home/runner/work/python-airslate/python-airslate/.venv/lib/python3.9/site-packages/pylint/lint/pylinter.py", line 922, in _check_file
    check_astroid_module(ast_node)
  File "/home/runner/work/python-airslate/python-airslate/.venv/lib/python3.9/site-packages/pylint/lint/pylinter.py", line 1054, in check_astroid_module
    retval = self._check_astroid_module(
  File "/home/runner/work/python-airslate/python-airslate/.venv/lib/python3.9/site-packages/pylint/lint/pylinter.py", line 1099, in _check_astroid_module
    walker.walk(ast_node)
  File "/home/runner/work/python-airslate/python-airslate/.venv/lib/python3.9/site-packages/pylint/utils/ast_walker.py", line 75, in walk
    self.walk(child)
  File "/home/runner/work/python-airslate/python-airslate/.venv/lib/python3.9/site-packages/pylint/utils/ast_walker.py", line 75, in walk
    self.walk(child)
  File "/home/runner/work/python-airslate/python-airslate/.venv/lib/python3.9/site-packages/pylint/utils/ast_walker.py", line 75, in walk
    self.walk(child)
  [Previous line repeated 2 more times]
  File "/home/runner/work/python-airslate/python-airslate/.venv/lib/python3.9/site-packages/pylint/utils/ast_walker.py", line 72, in walk
    callback(astroid)
  File "/home/runner/work/python-airslate/python-airslate/.venv/lib/python3.9/site-packages/pylint/checkers/refactoring/len_checker.py", line 61, in visit_call
    if not utils.is_call_of_name(node, "len"):
AttributeError: module 'pylint.checkers.utils' has no attribute 'is_call_of_name'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/runner/work/python-airslate/python-airslate/.venv/bin/pylint", line 8, in <module>
    sys.exit(run_pylint())
  File "/home/runner/work/python-airslate/python-airslate/.venv/lib/python3.9/site-packages/pylint/__init__.py", line 22, in run_pylint
    PylintRun(sys.argv[1:])
  File "/home/runner/work/python-airslate/python-airslate/.venv/lib/python3.9/site-packages/pylint/lint/run.py", line 349, in __init__
    linter.check(args)
  File "/home/runner/work/python-airslate/python-airslate/.venv/lib/python3.9/site-packages/pylint/lint/pylinter.py", line 866, in check
    check_parallel(
  File "/home/runner/work/python-airslate/python-airslate/.venv/lib/python3.9/site-packages/pylint/lint/check_parallel.py", line 102, in check_parallel
    for (
  File "/opt/hostedtoolcache/Python/3.9.1/x64/lib/python3.9/multiprocessing/pool.py", line 870, in next
    raise value
AttributeError: module 'pylint.checkers.utils' has no attribute 'is_call_of_name'
make: *** [Makefile:139: lint] Error 
Error: Process completed with exit code 2.
```

**Comment by sergeyklay** [comment]
Invalid repo to reporting the issue. Refs: https://github.com/PyCQA/pylint/issues/4097
